@startuml
package "Application_Layer" {
	component [main.sh] as main
	component [inputnum.sh] as inputnum
	component [logging_manager.sh] as logging	
	main .> inputnum : << import function >>
	main .> logging : << import function for logs >>

}

package "Logging_Layer" {
	file "test_while.log(Test: test_log)" as testlog
	file "prod_while.log(Prod: prod_log)" as prodlog
}

main -down-> testlog: << write  >> (Development)
main -down-> prodlog: << write  >> (Production)

@enduml
