@startuml
	class "main.sh" as main {
		+main()
}
	class "logging_manager.sh" as logging {
		+set_loggdir()
}
	class "input_num.sh" as inputnum {
		+input_digit()
}

main --> logging: import method and check log_dir
main --> inputnum: import method
@enduml
